import React from "react";

const TermsPolicy = () => {
  return (
    <>
      <div className="rbt-main-content mb--0 mr--0">
        <div className="rbt-daynamic-page-content center-width">
          <div className="rbt-dashboard-content">
            <div className="banner-area">
              <div className="settings-area">
                <h3 className="title">Terms of Service</h3>
              </div>
            </div>
            <div className="content-page pb--50">
              <div className="chat-box-list">
                <div className="content">
                  <h4>1. Acceptance of Terms</h4>
                  <p>By using the services provided by Oneclickhuman.com (“the Service”), you agree to be bound by the following Terms of Service ("TOS"). If you do not agree to these terms, you may not access or use the Service.</p>

                  <h4>2. Description of Service</h4>
                  <p>Oneclickhuman.com is a tool that converts refines AI-generated content to make it better and sound as natural as human content.</p>

                  <h4>3. User Obligations</h4>
                  <p>By using the Service, you agree to: Not reproduce, duplicate, copy, sell, or exploit any portion of the Service without explicit permission.</p>

                  <h4>4. Intellectual Property</h4>
                  <p>The Service and its original content, features, and functionality are owned by Oneclickhuman.com and are protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.</p>

                  <h4>5. Termination</h4>
                  <p>We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including, without limitation, if you breach the TOS.</p>

                  <h4>6. Limitation of Liability</h4>
                  <p>To the fullest extent permitted by law, Oneclickhuman.com shall not be liable for any indirect, incidental, special, consequential or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill or other intangible losses resulting from (a) your use or inability to use the Service; (b) any unauthorized access to or use of our servers and/or any personal information stored therein.</p>

                  <h4>7. Changes to TOS</h4>
                  <p>Oneclickhuman.com reserves the right to update or change the TOS at any time without notice. Your continued use of the Service after any modifications to the TOS will constitute your agreement to be bound by the modified TOS.</p>

                  <h4>8. Governing Law</h4>
                  <p>These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions.</p>

                  <h4>9. Contact Information</h4>
                  <p>For any questions regarding this TOS or the Service, please contact info@oneclickhuman.com. Prohibition of Plagiarism and Academic Misconduct</p>

                  <h4>10. Use for Ethical and Lawful Purposes</h4>
                  <p>Users of Oneclickhuman.com agree to utilize the Service in an ethical manner. Specifically: a. No Plagiarism: Users shall not use the Service to generate or produce content that plagiarizes or infringes upon the intellectual property rights of any third party, including copyrights, trademarks, or other proprietary rights. Users are responsible for ensuring that the content they generate using the Service is original and does not replicate existing materials in a manner that constitutes plagiarism. b. No Academic Misconduct: Users are prohibited from using the Service to engage in any form of academic misconduct, including but not limited to submitting any content generated by the Service as their own original work for academic credit, evaluation, or any other academic purpose. It is the user's responsibility to abide by the academic integrity policies of their respective educational institutions.</p>

                  <h4>11. Consequences for Misuse</h4>
                  <p> Any misuse of the Service, including generating plagiarized content or engaging in academic misconduct, can result in immediate termination of access to the Service, at the discretion of Oneclickhuman.com. Furthermore, users found in violation may be subject to other legal or academic consequences.</p>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default TermsPolicy;
